import { useCallback, useState } from 'react'
import { jsPDF } from 'jspdf'

function ExportPanel({
  baseBillPaise,
  taxPaise,
  tipPaise,
  grandTotalPaise,
  billInputs,
  payerName,
  peopleWithTotals,
  settlementTransfers,
  formatCurrency,
  ledgerUsers,
  ledgerBalances,
  ledgerRelations,
  savedBillsCount,
  onDownloadComplete,
}) {
  const [isGeneratingBill, setIsGeneratingBill] = useState(false)
  const [isGeneratingStats, setIsGeneratingStats] = useState(false)

  const dateString = new Intl.DateTimeFormat('en-IN', {
    dateStyle: 'full',
    timeStyle: 'short',
  }).format(new Date())

  const hasBillData = grandTotalPaise > 0
  const hasPeople = peopleWithTotals.length > 0
  const hasLedgerData = ledgerUsers.length > 0

  // ── Currency formatter for PDFs ──
  const fc = (paise) => {
    const val = (paise / 100).toFixed(2)
    return `Rs ${Number(val).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  }

  // ── Shared PDF helpers ──
  const drawLine = (doc, yPos, margin, pageW, color = [220, 225, 230]) => {
    doc.setDrawColor(...color)
    doc.setLineWidth(0.3)
    doc.line(margin, yPos, pageW - margin, yPos)
  }

  const addSection = (doc, title, yPos, margin) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(30, 41, 59)
    doc.text(title, margin, yPos)
    return yPos + 2
  }

  const addHeader = (doc, title, subtitle, margin, contentW, dateStr) => {
    let y = margin
    doc.setFillColor(15, 23, 42)
    doc.roundedRect(margin, y, contentW, 28, 4, 4, 'F')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(255, 255, 255)
    doc.text(title, margin + 8, y + 12)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(180, 190, 210)
    doc.text(subtitle, margin + 8, y + 19)

    const pageW = doc.internal.pageSize.getWidth()
    doc.text(dateStr, pageW - margin - 8, y + 12, { align: 'right' })

    return y + 36
  }

  const addFooter = (doc, margin, dateStr) => {
    const pageW = doc.internal.pageSize.getWidth()
    const footerY = doc.internal.pageSize.getHeight() - 12
    drawLine(doc, footerY - 4, margin, pageW, [230, 235, 240])
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(148, 163, 184)
    doc.text('Generated by Split the Bill', margin, footerY)
    doc.text(dateStr, pageW - margin, footerY, { align: 'right' })
  }

  // ── Bill Receipt PDF ──
  const generateBillPdf = useCallback(() => {
    setIsGeneratingBill(true)

    try {
      const doc = new jsPDF({ unit: 'mm', format: 'a4' })
      const pageW = doc.internal.pageSize.getWidth()
      const margin = 18
      const contentW = pageW - margin * 2

      let y = addHeader(doc, 'Split the Bill', 'Receipt & Settlement Report', margin, contentW, dateString)

      // ── Bill Breakdown ──
      y = addSection(doc, 'Bill Breakdown', y, margin)
      y += 5

      doc.setFillColor(248, 250, 252)
      doc.roundedRect(margin, y - 2, contentW, 38, 3, 3, 'F')

      const rows = [
        ['Base Bill', fc(baseBillPaise)],
        [`Tax${billInputs.taxMode === 'percent' ? ` (${billInputs.taxValue || 0}%)` : ''}`, fc(taxPaise)],
        [`Tip${billInputs.tipMode === 'percent' ? ` (${billInputs.tipValue || 0}%)` : ''}`, fc(tipPaise)],
      ]

      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)

      rows.forEach(([label, value]) => {
        doc.setTextColor(100, 116, 139)
        doc.text(label, margin + 6, y + 4)
        doc.setTextColor(30, 41, 59)
        doc.text(value, pageW - margin - 6, y + 4, { align: 'right' })
        y += 8
      })

      drawLine(doc, y, margin, pageW, [148, 163, 184])
      y += 5

      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.setTextColor(15, 23, 42)
      doc.text('Grand Total', margin + 6, y + 1)
      doc.text(fc(grandTotalPaise), pageW - margin - 6, y + 1, { align: 'right' })
      y += 14

      // ── Paid By ──
      if (payerName) {
        doc.setFillColor(239, 246, 255)
        doc.roundedRect(margin, y - 2, contentW, 12, 3, 3, 'F')
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        doc.setTextColor(100, 116, 139)
        doc.text('Paid by', margin + 6, y + 5)
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(37, 99, 235)
        doc.text(payerName, pageW - margin - 6, y + 5, { align: 'right' })
        y += 18
      }

      // ── People & Splits ──
      if (hasPeople) {
        y = addSection(doc, 'People & Splits', y, margin)
        y += 6

        doc.setFillColor(241, 245, 249)
        doc.roundedRect(margin, y - 3, contentW, 9, 2, 2, 'F')
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(8.5)
        doc.setTextColor(71, 85, 105)
        doc.text('NAME', margin + 6, y + 2)
        doc.text('SHARE', pageW - margin - 6, y + 2, { align: 'right' })
        y += 10

        peopleWithTotals.forEach((person, idx) => {
          if (y > 260) { doc.addPage(); y = margin }
          if (idx % 2 === 0) {
            doc.setFillColor(250, 251, 252)
            doc.rect(margin, y - 4, contentW, 9, 'F')
          }
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(10)
          doc.setTextColor(30, 41, 59)
          doc.text(person.name, margin + 6, y + 1)
          doc.setFont('helvetica', 'bold')
          doc.text(fc(person.splitSharePaise), pageW - margin - 6, y + 1, { align: 'right' })
          y += 9
        })
        y += 6
      }

      // ── Settlement ──
      if (settlementTransfers.length > 0) {
        if (y > 230) { doc.addPage(); y = margin }
        y = addSection(doc, 'Settlement Transfers', y, margin)
        y += 6

        settlementTransfers.forEach((transfer) => {
          if (y > 270) { doc.addPage(); y = margin }
          doc.setFillColor(254, 252, 232)
          doc.roundedRect(margin, y - 3, contentW, 11, 2, 2, 'F')
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(10)
          doc.setTextColor(30, 41, 59)
          doc.text(transfer.from, margin + 6, y + 3)
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(8)
          doc.setTextColor(161, 98, 7)
          const arrowText = 'pays  →'
          const arrowW = doc.getTextWidth(arrowText)
          doc.text(arrowText, pageW / 2 - arrowW / 2, y + 3)
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(10)
          doc.setTextColor(30, 41, 59)
          doc.text(`${transfer.to}  ${fc(transfer.amountPaise)}`, pageW - margin - 6, y + 3, { align: 'right' })
          y += 14
        })
      }

      addFooter(doc, margin, dateString)

      const filename = `split-the-bill-${new Date().toISOString().slice(0, 10)}.pdf`
      doc.save(filename)
      onDownloadComplete?.(filename)
    } catch (err) {
      console.error('PDF generation failed:', err)
    } finally {
      setIsGeneratingBill(false)
    }
  }, [baseBillPaise, billInputs, dateString, grandTotalPaise, hasPeople, onDownloadComplete, payerName, peopleWithTotals, settlementTransfers, taxPaise, tipPaise])

  // ── Overall Statistics PDF ──
  const generateStatsPdf = useCallback(() => {
    setIsGeneratingStats(true)

    try {
      const doc = new jsPDF({ unit: 'mm', format: 'a4' })
      const pageW = doc.internal.pageSize.getWidth()
      const margin = 18
      const contentW = pageW - margin * 2

      let y = addHeader(doc, 'Split the Bill', 'Overall Statistics & Ledger', margin, contentW, dateString)

      // ── Summary card ──
      doc.setFillColor(248, 250, 252)
      doc.roundedRect(margin, y - 2, contentW, 16, 3, 3, 'F')
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(10)
      doc.setTextColor(100, 116, 139)
      doc.text('Total saved bills:', margin + 6, y + 5)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(30, 41, 59)
      doc.text(String(savedBillsCount), margin + 45, y + 5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(100, 116, 139)
      doc.text('People involved:', pageW / 2 + 4, y + 5)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(30, 41, 59)
      doc.text(String(ledgerUsers.length), pageW / 2 + 44, y + 5)
      y += 22

      // ── Net Balances ──
      y = addSection(doc, 'Net Balances', y, margin)
      y += 6

      doc.setFillColor(241, 245, 249)
      doc.roundedRect(margin, y - 3, contentW, 9, 2, 2, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8.5)
      doc.setTextColor(71, 85, 105)
      doc.text('PERSON', margin + 6, y + 2)
      doc.text('STATUS', pageW / 2, y + 2, { align: 'center' })
      doc.text('AMOUNT', pageW - margin - 6, y + 2, { align: 'right' })
      y += 10

      ledgerBalances.forEach((entry, idx) => {
        if (y > 265) { doc.addPage(); y = margin }

        if (idx % 2 === 0) {
          doc.setFillColor(250, 251, 252)
          doc.rect(margin, y - 4, contentW, 9, 'F')
        }

        doc.setFont('helvetica', 'normal')
        doc.setFontSize(10)
        doc.setTextColor(30, 41, 59)
        doc.text(entry.name, margin + 6, y + 1)

        const isPositive = entry.balancePaise >= 0
        doc.setFont('helvetica', 'normal')
        doc.setFontSize(9)
        doc.setTextColor(...(isPositive ? [5, 150, 105] : [225, 29, 72]))
        doc.text(isPositive ? 'To Receive' : 'Owes', pageW / 2, y + 1, { align: 'center' })

        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        doc.text(fc(Math.abs(entry.balancePaise)), pageW - margin - 6, y + 1, { align: 'right' })
        y += 9
      })

      y += 8

      // ── Pairwise Breakdown ──
      if (y > 220) { doc.addPage(); y = margin }
      y = addSection(doc, 'Pairwise Breakdown', y, margin)
      y += 6

      ledgerRelations.forEach((user) => {
        if (user.relations.length === 0) return

        if (y > 250) { doc.addPage(); y = margin }

        // User header
        doc.setFillColor(241, 245, 249)
        doc.roundedRect(margin, y - 3, contentW, 9, 2, 2, 'F')

        const userBalance = ledgerBalances.find((b) => b.id === user.id)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        doc.setTextColor(30, 41, 59)
        doc.text(user.name, margin + 6, y + 2)

        if (userBalance) {
          const isPos = userBalance.balancePaise >= 0
          doc.setFont('helvetica', 'bold')
          doc.setFontSize(9)
          doc.setTextColor(...(isPos ? [5, 150, 105] : [225, 29, 72]))
          doc.text(
            `Net: ${isPos ? '+' : '-'}${fc(Math.abs(userBalance.balancePaise))}`,
            pageW - margin - 6, y + 2, { align: 'right' }
          )
        }

        y += 11

        user.relations.forEach((relation) => {
          if (y > 270) { doc.addPage(); y = margin }

          const isPositive = relation.amountPaise > 0
          const label = isPositive
            ? `${relation.name} owes ${user.name}`
            : `${user.name} owes ${relation.name}`

          doc.setFont('helvetica', 'normal')
          doc.setFontSize(9)
          doc.setTextColor(71, 85, 105)
          doc.text(label, margin + 10, y + 1)

          doc.setFont('helvetica', 'bold')
          doc.setTextColor(...(isPositive ? [5, 150, 105] : [225, 29, 72]))
          doc.text(
            `${isPositive ? '+' : '-'}${fc(Math.abs(relation.amountPaise))}`,
            pageW - margin - 6, y + 1, { align: 'right' }
          )
          y += 7
        })

        y += 5
      })

      addFooter(doc, margin, dateString)

      const filename = `split-the-bill-stats-${new Date().toISOString().slice(0, 10)}.pdf`
      doc.save(filename)
      onDownloadComplete?.(filename)
    } catch (err) {
      console.error('Stats PDF generation failed:', err)
    } finally {
      setIsGeneratingStats(false)
    }
  }, [dateString, ledgerBalances, ledgerRelations, ledgerUsers, onDownloadComplete, savedBillsCount])

  // ── Download button helper ──
  const DownloadButton = ({ onClick, disabled, isLoading, label }) => (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled || isLoading}
      className="flex w-full items-center justify-center gap-2.5 rounded-2xl bg-indigo-600 px-5 py-3.5 text-sm font-semibold text-white shadow-sm transition-all duration-300 ease-out hover:bg-indigo-500 hover:scale-[1.02] focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-slate-500 disabled:hover:scale-100"
    >
      {isLoading ? (
        <>
          <svg className="h-4 w-4 animate-spin" viewBox="0 0 24 24" fill="none">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
          </svg>
          Generating…
        </>
      ) : (
        <>
          <svg className="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
            <path d="M10.75 2.75a.75.75 0 00-1.5 0v8.614L6.295 8.235a.75.75 0 10-1.09 1.03l4.25 4.5a.75.75 0 001.09 0l4.25-4.5a.75.75 0 00-1.09-1.03l-2.955 3.129V2.75z" />
            <path d="M3.5 12.75a.75.75 0 00-1.5 0v2.5A2.75 2.75 0 004.75 18h10.5A2.75 2.75 0 0018 15.25v-2.5a.75.75 0 00-1.5 0v2.5c0 .69-.56 1.25-1.25 1.25H4.75c-.69 0-1.25-.56-1.25-1.25v-2.5z" />
          </svg>
          {label}
        </>
      )}
    </button>
  )

  return (
    <>
      {/* Left column – Previews */}
      <div className="space-y-6">
        {/* Current Bill Preview */}
        <section className="rounded-4xl border border-white/10 bg-white/5 p-6 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] backdrop-blur-xl sm:p-8">
          <div className="mb-5">
            <h2 className="text-xl font-semibold tracking-tight text-white">Current Bill Receipt</h2>
            <p className="mt-1 text-sm text-slate-400">Preview of the active bill on the Bill & Payment tab.</p>
          </div>

          <div className="space-y-4 rounded-3xl border border-white/10 bg-black/20 p-5">
            <div>
              <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Bill Breakdown</h3>
              <div className="mt-3 space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-400">Base Bill</span>
                  <span className="font-medium text-white">{formatCurrency(baseBillPaise)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-400">Tax{billInputs.taxMode === 'percent' ? ` (${billInputs.taxValue || 0}%)` : ''}</span>
                  <span className="font-medium text-white">{formatCurrency(taxPaise)}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-400">Tip{billInputs.tipMode === 'percent' ? ` (${billInputs.tipValue || 0}%)` : ''}</span>
                  <span className="font-medium text-white">{formatCurrency(tipPaise)}</span>
                </div>
                <div className="mt-1 border-t border-white/10 pt-2">
                  <div className="flex justify-between">
                    <span className="text-sm font-semibold text-slate-300">Grand Total</span>
                    <span className="text-sm font-bold text-white">{formatCurrency(grandTotalPaise)}</span>
                  </div>
                </div>
              </div>
            </div>

            {payerName && (
              <div className="rounded-2xl bg-indigo-500/10 border border-indigo-500/20 px-4 py-2.5">
                <div className="flex justify-between text-sm">
                  <span className="text-indigo-400">Paid by</span>
                  <span className="font-semibold text-indigo-300">{payerName}</span>
                </div>
              </div>
            )}

            {hasPeople && (
              <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">People & Shares</h3>
                <ul className="mt-3 space-y-1.5">
                  {peopleWithTotals.map((person) => (
                    <li key={person.id} className="flex items-center justify-between rounded-xl bg-white/5 border border-white/5 px-3 py-2 text-sm">
                      <span className="text-slate-300">{person.name}</span>
                      <span className="font-semibold text-white">{formatCurrency(person.splitSharePaise)}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {settlementTransfers.length > 0 && (
              <div>
                <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Settlement</h3>
                <ul className="mt-3 space-y-1.5">
                  {settlementTransfers.map((transfer, idx) => (
                    <li key={idx} className="flex items-center justify-between rounded-xl bg-amber-500/10 border border-amber-500/20 px-3 py-2 text-sm">
                      <span className="text-slate-300">{transfer.from} <span className="text-amber-500/50">→</span> <span className="text-white font-medium">{transfer.to}</span></span>
                      <span className="font-semibold text-amber-400">{formatCurrency(transfer.amountPaise)}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {!hasBillData && (
              <p className="py-4 text-center text-sm text-slate-500">No bill data yet. Fill in the Bill & Payment tab first.</p>
            )}
          </div>
        </section>

        {/* Overall Statistics Preview */}
        <section className="rounded-4xl border border-white/10 bg-white/5 p-6 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] backdrop-blur-xl sm:p-8">
          <div className="mb-5">
            <h2 className="text-xl font-semibold tracking-tight text-white">Overall Statistics</h2>
            <p className="mt-1 text-sm text-slate-400">Aggregated balances across all {savedBillsCount} saved bill{savedBillsCount !== 1 ? 's' : ''}.</p>
          </div>

          <div className="space-y-4 rounded-3xl border border-white/10 bg-black/20 p-5">
            {!hasLedgerData ? (
              <p className="py-4 text-center text-sm text-slate-500">No saved bills yet. Save a bill first to see statistics.</p>
            ) : (
              <>
                <div>
                  <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Net Balances</h3>
                  <ul className="mt-3 space-y-1.5">
                    {ledgerBalances.map((entry) => (
                      <li key={entry.id} className="flex items-center justify-between rounded-xl bg-white/5 border border-white/5 px-3 py-2 text-sm">
                        <span className="text-slate-300">{entry.name}</span>
                        <span className={`font-semibold ${entry.balancePaise >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                          {entry.balancePaise >= 0 ? '+' : '-'}{formatCurrency(Math.abs(entry.balancePaise))}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div>
                  <h3 className="text-xs font-semibold uppercase tracking-wider text-slate-500">Pairwise Breakdown</h3>
                  <div className="mt-3 space-y-3">
                    {ledgerRelations.filter((u) => u.relations.length > 0).map((user) => (
                      <div key={user.id} className="rounded-xl border border-white/10 bg-black/40 p-3">
                        <div className="flex items-center justify-between">
                          <span className="text-sm font-semibold text-white">{user.name}</span>
                          {(() => {
                            const bal = ledgerBalances.find((b) => b.id === user.id)
                            if (!bal) return null
                            return (
                              <span className={`text-xs font-semibold ${bal.balancePaise >= 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                                Net: {bal.balancePaise >= 0 ? '+' : '-'}{formatCurrency(Math.abs(bal.balancePaise))}
                              </span>
                            )
                          })()}
                        </div>
                        <ul className="mt-2 space-y-1">
                          {user.relations.map((rel) => (
                            <li key={rel.id} className="flex justify-between text-xs text-slate-400">
                              <span>{rel.amountPaise > 0 ? <><span className="text-white font-medium">{rel.name}</span> owes {user.name}</> : <>{user.name} owes <span className="text-white font-medium">{rel.name}</span></>}</span>
                              <span className={`font-semibold ${rel.amountPaise > 0 ? 'text-emerald-400' : 'text-rose-400'}`}>
                                {rel.amountPaise > 0 ? '+' : '-'}{formatCurrency(Math.abs(rel.amountPaise))}
                              </span>
                            </li>
                          ))}
                        </ul>
                      </div>
                    ))}
                  </div>
                </div>
              </>
            )}
          </div>
        </section>
      </div>

      {/* Right column – Download actions */}
      <div className="space-y-6">
        {/* Current Bill Download */}
        <section className="rounded-4xl border border-white/10 bg-white/5 p-6 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] backdrop-blur-xl sm:p-8">
          <div className="mb-5">
            <h2 className="text-xl font-semibold tracking-tight text-white">Download Receipt</h2>
            <p className="mt-1 text-sm text-slate-400">Save the current bill as a professional PDF.</p>
          </div>

          <div className="space-y-4">
            <div className="rounded-3xl border border-white/10 bg-white/5 p-5 text-center">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-rose-500/20 border border-rose-500/30 shadow-sm">
                <svg className="h-7 w-7 text-rose-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                </svg>
              </div>
              <p className="mt-3 text-sm font-semibold text-white">
                {hasBillData ? 'Receipt ready' : 'No bill data'}
              </p>
              <p className="mt-0.5 text-xs text-slate-400">
                {hasBillData
                  ? `${peopleWithTotals.length} ${peopleWithTotals.length === 1 ? 'person' : 'people'} · ${formatCurrency(grandTotalPaise)}`
                  : 'Enter bill details first.'}
              </p>
            </div>

            <DownloadButton
              onClick={generateBillPdf}
              disabled={!hasBillData}
              isLoading={isGeneratingBill}
              label="Download Receipt PDF"
            />
          </div>
        </section>

        {/* Overall Stats Download */}
        <section className="rounded-4xl border border-white/10 bg-white/5 p-6 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] backdrop-blur-xl sm:p-8">
          <div className="mb-5">
            <h2 className="text-xl font-semibold tracking-tight text-white">Download Statistics</h2>
            <p className="mt-1 text-sm text-slate-400">Export the overall ledger across all saved bills.</p>
          </div>

          <div className="space-y-4">
            <div className="rounded-3xl border border-white/10 bg-white/5 p-5 text-center">
              <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-500/20 border border-indigo-500/30 shadow-sm">
                <svg className="h-7 w-7 text-indigo-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M3 13.125C3 12.504 3.504 12 4.125 12h2.25c.621 0 1.125.504 1.125 1.125v6.75C7.5 20.496 6.996 21 6.375 21h-2.25A1.125 1.125 0 013 19.875v-6.75zM9.75 8.625c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125v11.25c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V8.625zM16.5 4.125c0-.621.504-1.125 1.125-1.125h2.25C20.496 3 21 3.504 21 4.125v15.75c0 .621-.504 1.125-1.125 1.125h-2.25a1.125 1.125 0 01-1.125-1.125V4.125z" />
                </svg>
              </div>
              <p className="mt-3 text-sm font-semibold text-white">
                {hasLedgerData ? 'Statistics ready' : 'No saved data'}
              </p>
              <p className="mt-0.5 text-xs text-slate-400">
                {hasLedgerData
                  ? `${savedBillsCount} bill${savedBillsCount !== 1 ? 's' : ''} · ${ledgerUsers.length} ${ledgerUsers.length === 1 ? 'person' : 'people'}`
                  : 'Save at least one bill first.'}
              </p>
            </div>

            <DownloadButton
              onClick={generateStatsPdf}
              disabled={!hasLedgerData}
              isLoading={isGeneratingStats}
              label="Download Statistics PDF"
            />
          </div>
        </section>

        {/* Tips card */}
        <section className="rounded-4xl border border-white/10 bg-white/5 p-6 shadow-[0_8px_32px_0_rgba(0,0,0,0.3)] backdrop-blur-xl sm:p-8">
          <h3 className="text-sm font-semibold text-white">Tips</h3>
          <ul className="mt-3 space-y-2 text-sm text-slate-400">
            <li className="flex gap-2">
              <span className="mt-0.5 text-indigo-400">•</span>
              <span><strong className="text-slate-200">Receipt PDF</strong> contains the current bill, splits, and settlement.</span>
            </li>
            <li className="flex gap-2">
              <span className="mt-0.5 text-purple-400">•</span>
              <span><strong className="text-slate-200">Statistics PDF</strong> contains net balances and pairwise breakdowns across all saved bills.</span>
            </li>
            <li className="flex gap-2">
              <span className="mt-0.5 text-indigo-400">•</span>
              Share either PDF via WhatsApp, email, or any messaging app.
            </li>
          </ul>
        </section>
      </div>
    </>
  )
}

export default ExportPanel
